### ISSUE TITLE
Promise & async/await support

### ISSUE THREAD

**Issue by R-omk** [vitaliy-art/tarantoolscript#39]
This is a feature for future development.

In typescripttolua, there is already support for `Promise`, which generates code based on native Lua coroutines. In the case of tarantool, the transpiler needs to be extended with plugins that generate different code, based on the fiber system built into tarantool.

My idea is to use a pool of fibers that take tasks through channels and return results, instead of creating a new fiber for each asynchronous request/promise.

At this point, this is a raw idea, but I see the advantage of supporting async/await because there are already many libraries written in TypeScript. Why not try taking another step to enable using them with minimal changes, or maybe even without any changes at all?

The motivation for this approach came from my acquaintance with [this Go library](https://github.com/chebyrash/promise)  , which implements the promise principles using synchronization primitives that are built into the language.

**Comment by vitaliy-art** [comment]
I sure feature with async/await is great idea, but this is out of scope for this project. Tarantoolscript is just a declarations of Tarantool modules and it contains no any logical code (`library` build mode). Any new non-declaration code should be included into separated repository, and i hope it can be written with Tarantoolscript.
